ARG VERSION=11.5.2

FROM grafana/grafana-oss:${VERSION}

# copy the datasources and dashboards
COPY datasources /etc/grafana/provisioning/datasources
COPY provisioning/dashboards /etc/grafana/provisioning/dashboards

# copy and set permissions for entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# use custom entrypoint
ENTRYPOINT ["/entrypoint.sh"]